services:
  - type: web
    name: ff-player-api
    runtime: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn server.app:app --bind 0.0.0.0:$PORT
    plan: free
